# ui/resources/languages.py

DASHBOARD_LANGS = {
    'TR': {
        'logo': "☁️ MySaaS Workspace", 'menu_title': "SUNUCULARIM",
        'status_online': "🟢", 'status_offline': "⚫", 'logout_tip': "Ayarlar / Çıkış",
        'theme_dark': "🌙 Koyu Tema", 'theme_light': "☀️ Açık Tema",
        'select_title': "Çalışma Modelinizi Seçin", 'select_sub': "İhtiyaçlarınıza en uygun kullanım türünü belirleyerek başlayın.",
        'std_card_title': "Standart Kullanıcı", 'std_card_desc': "Bireysel kullanım için temel özellikler ve 1 sunucu hakkı.", 'btn_continue': "Ücretsiz Devam Et",
        'ent_card_title': "Enterprise (Premium)", 'ent_card_desc': "Ekipler ve şirketler için sınırsız erişim ve gelişmiş özellikler.", 'btn_examine': "Paketi İncele",
        'welcome_title': "MySaaS'a Hoş Geldiniz!", 'welcome_sub': "Çalışmaya başlamak için aşağıdaki seçeneklerden birini seçin.",
        'card_create_title': "Sunucu Oluştur", 'card_create_desc': "Kendi topluluğunuzu veya özel çalışma alanınızı kurun.", 'card_create_btn': "Oluştur",
        'card_join_title': "Sunucuya Katıl", 'card_join_desc': "Elinizdeki davet bağlantısı ile mevcut bir sunucuya katılın.", 'card_join_btn': "Katıl",
        'card_friend_title': "Arkadaş Ekle", 'card_friend_desc': "Arkadaşlarınızı ekleyerek anında direkt mesajlaşmaya başlayın.", 'card_friend_btn': "Ekle",
        'ent_pay_title': "Enterprise Paket İçeriği", 'ent_pay_price': "$9.99 / Aylık",
        'ent_f1': "★ Sınırsız Sunucu ve Çalışma Panosu", 'ent_f2': "★ Gelişmiş Görüntülü Arama & Sesli Sohbet",
        'ent_f3': "★ Sınırsız Dosya Yükleme Kapasitesi", 'ent_f4': "★ 7/24 Öncelikli Teknik Destek",
        'btn_pay': "💳 Ödeme Yap", 'btn_back': "⬅ Geri Dön",
        'setup_title': "Sunucu Kurulum ve Ayarları", 'setup_sub': "Yeni çalışma alanınıza bir isim verin ve ekibinizi toplamaya başlayın.",
        'setup_btn_icon': "📷 Sunucu İkonu Yükle (Opsiyonel)", 'setup_ph': "Sunucu Adı (Örn: Proje X Ekibi)", 
        'setup_btn_create': "🚀 Sunucuyu Kur", 'setup_btn_cancel': "İptal",
        'dlg_join_title': "Bir Sunucuya Katıl", 'dlg_join_sub': "Arkadaşınızdan aldığınız davet kodunu veya bağlantısını aşağıya girin.",
        'dlg_join_ph': "Davet Kodu veya URL", 'dlg_btn_cancel': "İptal",
        'search_title': "Arkadaş Bul & Ekle", 'search_sub': "Kullanıcı adı veya e-posta adresi ile arkadaşlarınızı arayın.",
        'search_ph': "Kullanıcı Adı veya E-posta...", 'search_no_result': "Kullanıcı bulunamadı.", 'search_btn_add': "Ekle", 'search_btn_close': "Kapat",
        'err_invalid_invite': "Geçersiz veya süresi dolmuş bir davet kodu girdiniz!",
        'err_freemium_limit': "Ücretsiz planda maksimum sunucu limitinize (1) ulaştınız. Lütfen Enterprise pakete yükseltin.",
        'err_401': "Oturum süreniz dolmuş veya geçersiz (401). Lütfen tekrar giriş yapın.",
        'no_servers': "📌 Henüz sunucu yok",
        'cat_text': "💬 METİN KANALLARI", 'cat_board': "📋 PANO KANALLARI",
        'chat_ph': "Mesajınızı yazın...", 'btn_send': "Gönder",
        'tip_mic': "Mikrofonu Aç/Kapat", 'tip_deaf': "Sesi Aç/Kapat",
        'home_btn': "Ana Sayfa", 'friends_title': "👥 Arkadaşlar", 'friends_online': "Çevrimiçi", 'friends_all': "Tümü",
        'friends_search': "Arkadaşlarda Ara...", 'friends_empty': "Henüz arkadaş listeniz boş.", 'btn_search_friend': "🔍 Arkadaş Ara",
        'set_cat_personal': "👤 Kişisel Ayarlar", 'set_cat_server': "🏢 Sunucu Ayarları", 'set_cat_logout': "🚪 Çıkış Yap",
        'set_close': "✖ Kapat (ESC)", 'set_pers_title': "Hesabım", 'set_pers_name': "Kullanıcı Adı", 'set_pers_email': "E-posta Adresi",
        'set_pers_save': "Değişiklikleri Kaydet", 'set_srv_title': "Sunucu Ayarları (Genel)", 'set_srv_desc': "Yönetici olduğunuz sunucuların genel ayarlarını buradan yapılandırabilirsiniz.",
        'set_avatar_btn': "Fotoğraf Yükle",
        'set_acc_title': "Hesap Bilgileri",
        'set_acc_type': "Hesap Türü: Standart",
        'set_acc_limit': "Sunucu Kurma Hakkı: 1",
        'set_acc_upgrade': "🚀 Enterprise'a Yükselt ($9.99/Aylık)",
        'set_pass_title': "Şifre Değiştir",
        'set_pass_old': "Mevcut Şifre",
        'set_pass_new': "Yeni Şifre",
        'set_pass_rep': "Yeni Şifre (Tekrar)"
    },
    'EN': {
        'logo': "☁️ MySaaS Workspace", 'menu_title': "MY SERVERS",
        'status_online': "🟢", 'status_offline': "⚫", 'logout_tip': "Settings / Logout",
        'theme_dark': "🌙 Dark Mode", 'theme_light': "☀️ Light Mode",
        'select_title': "Choose Your Working Model", 'select_sub': "Start by selecting the plan that best fits your needs.",
        'std_card_title': "Standard User", 'std_card_desc': "Basic features for individual use and 1 server limit.", 'btn_continue': "Continue for Free",
        'ent_card_title': "Enterprise (Premium)", 'ent_card_desc': "Unlimited access and advanced features for teams and companies.", 'btn_examine': "View Package",
        'welcome_title': "Welcome to MySaaS!", 'welcome_sub': "Choose one of the options below to get started.",
        'card_create_title': "Create Server", 'card_create_desc': "Set up your own community or private workspace.", 'card_create_btn': "Create",
        'card_join_title': "Join Server", 'card_join_desc': "Join an existing server using an invite link.", 'card_join_btn': "Join",
        'card_friend_title': "Add Friend", 'card_friend_desc': "Add your friends to start direct messaging instantly.", 'card_friend_btn': "Add Friend",
        'ent_pay_title': "Enterprise Package Details", 'ent_pay_price': "$9.99 / Month",
        'ent_f1': "★ Unlimited Servers and Workspaces", 'ent_f2': "★ Advanced Video & Voice Chat",
        'ent_f3': "★ Unlimited File Upload Capacity", 'ent_f4': "★ 24/7 Priority Technical Support",
        'btn_pay': "💳 Make Payment", 'btn_back': "⬅ Go Back",
        'setup_title': "Server Setup & Settings", 'setup_sub': "Give your new workspace a name and start gathering your team.",
        'setup_btn_icon': "📷 Upload Server Icon (Optional)", 'setup_ph': "Server Name (e.g. Project X Team)", 
        'setup_btn_create': "🚀 Create Server", 'setup_btn_cancel': "Cancel",
        'dlg_join_title': "Join a Server", 'dlg_join_sub': "Enter an invite code or link provided by your friend below.",
        'dlg_join_ph': "Invite Code or URL", 'dlg_btn_cancel': "Cancel",
        'search_title': "Find & Add Friends", 'search_sub': "Search for friends using their username or email address.",
        'search_ph': "Username or Email...", 'search_no_result': "No users found.", 'search_btn_add': "Add", 'search_btn_close': "Close",
        'err_invalid_invite': "You have entered an invalid or expired invite code!",
        'err_freemium_limit': "You have reached your maximum server limit (1) on the free plan. Please upgrade.",
        'err_401': "Session expired or invalid (401). Please log in again.",
        'no_servers': "📌 No servers yet",
        'cat_text': "💬 TEXT CHANNELS", 'cat_board': "📋 BOARD CHANNELS",
        'chat_ph': "Type your message...", 'btn_send': "Send",
        'tip_mic': "Toggle Microphone", 'tip_deaf': "Toggle Audio",
        'home_btn': "Home", 'friends_title': "👥 Friends", 'friends_online': "Online", 'friends_all': "All",
        'friends_search': "Search Friends...", 'friends_empty': "Your friends list is currently empty.", 'btn_search_friend': "🔍 Search Friend",
        'set_cat_personal': "👤 Personal Settings", 'set_cat_server': "🏢 Server Settings", 'set_cat_logout': "🚪 Logout",
        'set_close': "✖ Close (ESC)", 'set_pers_title': "My Account", 'set_pers_name': "Username", 'set_pers_email': "Email Address",
        'set_pers_save': "Save Changes", 'set_srv_title': "Server Settings (Global)", 'set_srv_desc': "Configure global settings for the servers you manage here.",
        'set_avatar_btn': "Upload Photo", 'set_acc_title': "Account Information", 'set_acc_type': "Account Type: Standard",
        'set_acc_limit': "Server Limit: 1", 'set_acc_upgrade': "🚀 Upgrade to Enterprise ($9.99/Month)",
        'set_pass_title': "Change Password", 'set_pass_old': "Current Password", 'set_pass_new': "New Password", 'set_pass_rep': "Repeat New Password"
    },
    'GER': {
        'logo': "☁️ MySaaS Workspace", 'menu_title': "MEINE SERVER",
        'status_online': "🟢", 'status_offline': "⚫", 'logout_tip': "Einstellungen / Abmelden",
        'theme_dark': "🌙 Dunkel", 'theme_light': "☀️ Hell",
        'select_title': "Wählen Sie Ihr Arbeitsmodell", 'select_sub': "Beginnen Sie mit der Auswahl des Plans.",
        'std_card_title': "Standardbenutzer", 'std_card_desc': "Grundlegende Funktionen für Einzelpersonen (1 Server-Limit).", 'btn_continue': "Kostenlos fortfahren",
        'ent_card_title': "Enterprise (Premium)", 'ent_card_desc': "Unbegrenzter Zugang und erweiterte Funktionen für Teams.", 'btn_examine': "Paket ansehen",
        'welcome_title': "Willkommen bei MySaaS!", 'welcome_sub': "Wählen Sie eine der untenstehenden Optionen, um zu beginnen.",
        'card_create_title': "Server erstellen", 'card_create_desc': "Richten Sie Ihre eigene Community oder Ihren Arbeitsbereich ein.", 'card_create_btn': "Erstellen",
        'card_join_title': "Server beitreten", 'card_join_desc': "Treten Sie einem Server mit einem Einladungslink bei.", 'card_join_btn': "Beitreten",
        'card_friend_title': "Freund hinzufügen", 'card_friend_desc': "Fügen Sie Freunde hinzu, um Direktnachrichten zu senden.", 'card_friend_btn': "Hinzufügen",
        'ent_pay_title': "Enterprise-Paket Details", 'ent_pay_price': "$9.99 / Monat",
        'ent_f1': "★ Unbegrenzte Server und Arbeitsbereiche", 'ent_f2': "★ Erweiterter Video- & Voice-Chat",
        'ent_f3': "★ Unbegrenzte Datei-Upload-Kapazität", 'ent_f4': "★ 24/7 Priority Technischer Support",
        'btn_pay': "💳 Bezahlen", 'btn_back': "⬅ Zurück",
        'setup_title': "Server-Setup & Einstellungen", 'setup_sub': "Geben Sie Ihrem neuen Arbeitsbereich einen Namen und beginnen Sie.",
        'setup_btn_icon': "📷 Server-Symbol hochladen (Optional)", 'setup_ph': "Servername (z.B. Projekt X)", 
        'setup_btn_create': "🚀 Server erstellen", 'setup_btn_cancel': "Abbrechen",
        'dlg_join_title': "Einem Server beitreten", 'dlg_join_sub': "Geben Sie unten einen Einladungscode oder -link ein.",
        'dlg_join_ph': "Einladungscode oder URL", 'dlg_btn_cancel': "Abbrechen",
        'search_title': "Freunde finden & hinzufügen", 'search_sub': "Suchen Sie nach Freunden anhand ihres Benutzernamens oder E-Mail.",
        'search_ph': "Benutzername oder E-Mail...", 'search_no_result': "Keine Benutzer gefunden.", 'search_btn_add': "Hinzufügen", 'search_btn_close': "Schließen",
        'err_invalid_invite': "Sie haben einen ungültigen Einladungscode eingegeben!",
        'err_freemium_limit': "Sie haben das maximale Serverlimit erreicht. Bitte upgraden Sie auf Enterprise.",
        'err_401': "Sitzung abgelaufen oder ungültig (401). Bitte loggen Sie sich erneut ein.",
        'no_servers': "📌 Noch keine Server",
        'cat_text': "💬 TEXTKANÄLE", 'cat_board': "📋 BOARD-KANÄLE",
        'chat_ph': "Nachricht eingeben...", 'btn_send': "Senden",
        'tip_mic': "Mikrofon umschalten", 'tip_deaf': "Audio umschalten",
        'home_btn': "Startseite", 'friends_title': "👥 Freunde", 'friends_online': "Online", 'friends_all': "Alle",
        'friends_search': "Freunde suchen...", 'friends_empty': "Ihre Freundesliste ist derzeit leer.", 'btn_search_friend': "🔍 Freunde suchen",
        'set_cat_personal': "👤 Persönliche Einstellungen", 'set_cat_server': "🏢 Servereinstellungen", 'set_cat_logout': "🚪 Abmelden",
        'set_close': "✖ Schließen (ESC)", 'set_pers_title': "Mein Konto", 'set_pers_name': "Benutzername", 'set_pers_email': "E-Mail-Adresse",
        'set_pers_save': "Änderungen speichern", 'set_srv_title': "Servereinstellungen (Global)", 'set_srv_desc': "Konfigurieren Sie hier die globalen Einstellungen für die von Ihnen verwalteten Server.",
        'set_avatar_btn': "Foto hochladen", 'set_acc_title': "Kontoinformationen", 'set_acc_type': "Kontotyp: Standard",
        'set_acc_limit': "Serverlimit: 1", 'set_acc_upgrade': "🚀 Auf Enterprise upgraden ($9.99/Monat)",
        'set_pass_title': "Passwort ändern", 'set_pass_old': "Aktuelles Passwort", 'set_pass_new': "Neues Passwort", 'set_pass_rep': "Neues Passwort (Wiederholen)"
    }
}